config/routes.rb
Rails.application.routes.draw do
  get 'questions/index'
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tips do
    resources :comments
  end 
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tip
end

app/models/tip.rb
class Tip < ApplicationRecord
    
    # can contain many comments for one tip. dependent on destroy
    has_many :comments, dependent: :destroy
    
    # specifies that the title must be present and contain at least five characters or tip will not be accepted
    validates :title, presence: true, length: { minimum: 5 }
    
    # specifies that the name must be present and contain at least two characters or tip will not be accepted
    validates :name, presence: true, length: { minimum: 2 }
    
    # specifies that the text must be populated with characters or numbers and contain at least ten characters or tip will not be accepted
    validates :text, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
#this controller regulates how the comments are handled
class CommentsController < ApplicationController
    
    # the def create is the mmethod for creating a comment on a tip
    def create
        @tip = Tip.find(params[:tip_id])
        @comment = @tip.comments.create(comment_params)
        redirect_to tip_path(@tip)
    end 
    
    # the def desroy is the method for deleting a comment on a tip
    def destroy
        @tip = Tip.find(params[:tip_id])
        @comment = @tip.comments.find(params[:id])
        @comment.destroy
        redirect_to tip_path(@tip)
    end 

    #def comment params.. 
    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end 
        
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
  end
end

app/controllers/tips_controller.rb
# this controller handles how tips within the application are handled
class TipsController < ApplicationController
    
    # this will display all tips in the database in a list
    def index
        @tips = Tip.all
    end
    
    # the method is used  to take the user to the new tip form 
    def new
        @tip = Tip.new
    end
    
    #the def create will take the parameters passed in and creates a new tip based on what was entered
    def create
        @tip = Tip.new(tip_params)
        if @tip.save
            redirect_to @tip
        else
            render 'new'
        end
    end
    
    # this method was created to find the specified tip and show it
    def show
        @tip = Tip.find(params[:id])
    end
    
    # this method was created to take the user to the tip edit page
    def edit
        @tip = Tip.find(params[:id])
    end
    
    #this method was created to update the tips. it will take the parameters and updates the specified tip
    def update
        @tip = Tip.find(params[:id])
        if @tip.update(tip_params)
            redirect_to @tip
        else
            render 'edit'
        end
    end
    
    # this method was created to destroy the specified tip
    def destroy
        @tip = Tip.find(params[:id])
        @tip.destroy
        
        redirect_to tips_path
    end
end

    #title, text, name, and category is taken
private
    def tip_params
        params.require(:tip).permit(:title, :text, :name, :category)
    end

app/controllers/welcome_controller.rb
#welcome controller
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<%-# commenter -%>
<p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
</p>
 <%-#comment -%>
<p>
    <strong>Comment:</strong>
    <%= comment.body %>
</p>
<%-#Destroy the comment  -%>
<p>
    <%= link_to 'Destroy Comment', [comment.tip, comment],
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%-#form for the tips  -%>
<%= form_for([@tip, @tip.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<%-#footer present  -%>

<footer class="footer">
     POWERED BY YEET-HAW
</footer>

app/views/layouts/_header.html.erb
<%-#Header present on each page  -%>
<%-#Navigation bar consists of HOme, General, Add tip, and Interview questions -%>

<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Interview Assistant", welcome_index_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Home', welcome_index_path %></li>
            <li><%= link_to 'General Tips', controller: 'tips' %></li>
            <li><%= link_to 'Add Tip', new_tip_path %></li>
            <li><%= link_to "Interview Questions",  questions_index_path%></li>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%-# Interview assistant applicatoin  -%>
<html>
  <head>
    <title>InterviewAssistant</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/questions/index.html.erb
<%-#Sample Interview Questions -%>
<header class="welcomeheader">
    <h1>Interview Questions</h1>
</header>
<%-# List of Questions -%>
<br>
<ul>
<li id = "list">Give an example of an occasion when you used logic to solve a problem.</li>
<li id = "list">Give an example of a goal you reached and tell me how you achieved it.</li>
<li id = "list">Give an example of a goal you didn't meet and how you handled it.</li>
<li id = "list">Describe a stressful situation at work and how you handled it.</li>
<li id = "list">Tell me about how you worked effectively under pressure.</li>
<li id = "list">How do you handle a challenge?</li>
<li id = "list">Have you been in a situation where you didn't have enough work to do?</li>
<li id = "list">Have you ever made a mistake? How did you handle it?</li>
<li id = "list">Describe a decision you made that was unpopular and how you handled implementing it.</li>
<li id = "list">Did you ever make a risky decision? Why? How did you handle it?</li>
<li id = "list">Did you ever postpone making a decision? Why?</li>
<li id = "list">Have you ever dealt with company policy you weren't in agreement with? How?</li>
<li id = "list">Have you gone above and beyond the call of duty? If so, how?</li>
<li id = "list">When you worked on multiple projects how did you prioritize?</li>
<li id = "list">How did you handle meeting a tight deadline?</li>
<li id = "list">Give an example of how you set goals and achieve them.</li>
<li id = "list">Did you ever not meet your goals? Why?</li>
<li id = "list">What do you do when your schedule is interrupted? Give an example of how you handle it.</li>
<li id = "list">Have you had to convince a team to work on a project they weren't thrilled about? How did you do it?</li>
<li id = "list">Give an example of how you've worked on a team.</li>
<li id = "list">Have you handled a difficult situation with a co-worker? How?</li>
<li id = "list">What do you do if you disagree with a co-worker?</li>
<li id = "list">Share an example of how you were able to motivate employees or co-workers.</li>
<li id = "list">Do you listen? Give an example of when you did or when you didn't listen.</li>
<li id = "list">Have you handled a difficult situation with a supervisor? How?</li>
<li id = "list">Have you handled a difficult situation with another department? How?</li>
<li id = "list">Have you handled a difficult situation with a client or vendor? How?</li>
<li id = "list">What do you do if you disagree with your boss?</li>
</ul>

app/views/tips/_form.html.erb
<%-#This is the form partial for the 'new' and 'edit' pages  -%>
<%= form_for @tip do |f| %>
  
  <%- #Specifies any errors that may arise -%>
  <% if @tip.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tip.errors.count, "error") %> prohibited
        this tip from being saved:
      </h2>
      <ul>
        <% @tip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
<%-# submit -%>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/tips/edit.html.erb
<%-#Editing the tips  -%>
<header class="welcomeheader">
    <h1>Editing Tip</h1>
</header>
<br>
<%-# calls on the form partial to render the view -%> 
<%= render 'form' %>
 
<%= link_to 'Back', tips_path %>

app/views/tips/index.html.erb
<%- #Specifies the view for the index page. This page lists all of the tips within the database, along with show, edit, and destroy buttons. -%>
<header class="welcomeheader">
  <h1>Listing Tips</h1>
</header>

<br>
 <%-# Table with titles included -%>
<table>
  <tr>
    <th>TITLE</th>
    <th>NAME</th>
    <th>TEXT</th>
  </tr>
 <%-# what each tip will do -%>
  <% @tips.each do |tip| %>
    <tr>
      <td><%= tip.title %></td>
      <td><%= tip.name %></td>
      <td><%= tip.text %></td>
      <td><%= link_to 'Show', tip_path(tip) %></td>
      <td><%= link_to 'Edit', edit_tip_path(tip) %></td>
 <%-#Destroy comment  -%>
      <td><%= link_to 'Destroy',
                                tip_path(tip),
                                method: :delete,
                                data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%-# Link to add a new tip that will direct you the appropriate page -%>
<%= link_to 'Add New Tip', new_tip_path %>

app/views/tips/new.html.erb
<header class="welcomeheader">
    <h1>New Tip</h1>
</header>
<br>
<%- #calls on the form partial to render the view -%> 
<%= render 'form' %>

<%= link_to 'Back', tips_path %>

app/views/tips/show.html.erb
<header class="welcomeheader">
  <h1>Current Tip</h1>
</header>
<br>
<% if false %>
<%-#This is the page that shows the tip specified by the user. -%>
<%-#It displays the title of the tip, the name of the individual who posted it, the text, and the associated comments.  -%>


<% end %>
<%-#Title header Creation -%>
  <p>
    <strong>Title:</strong>
    <%= @tip.title %>
  </p>
  
  <%-#Name header Creation -%>

  <p>
    <strong>Name:</strong>
    <%= @tip.name %>
  </p>
   
   <%-#Text header creation -%>

  <p>
    <strong>Text:</strong>
    <%= @tip.text %>
  </p>
  
  <%-#Comments Creation an adding a comment on the form -%>

 <h2>Comments</h2>
  <%= render @tip.comments %>

  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>
  
  <%= link_to 'Tips List', tips_path %>

app/views/welcome/index.html.erb
<%-#Welcome Page -%>

<header class="welcomeheader">
  <h1>Interview Assistant</h1>
  <p class="description">Expert help on professional interviews</p>
</header>

<%-#Description of what the application does -%>

<br>
    <h3>What do we do?</h3>
    <br>
    <div class="row">
        <div class="column">
            <p>
                Hello! Welcome to the Interview Assistant, where all the answers related to professional interviews are answered. We know that interviews can be quite scary, especially if it is your first time.
                With our tips and interview questions, we can alleviate any anxiety you might have towards the interview process. Our interview questions will cover a variety of topics including salary inquiries and
                behavioral questions, which are extremely common. Going through are our interview questions and creating customized responses for them will be incredibly helpful to your success in hunting for either
                jobs, internships, or co-ops. Our tips, which come from both our personal experiences and professionals, will provide their insight as well. It will prepare you for situations that you may not be ready for
                We are here to aid in your pursuit of success.
            </p>
        </div>
        <%-#image inserted -%>

        <div class="column">
            <img src="https://images.unsplash.com/photo-1507679799987-c73779587ccf?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=2f2507356905735cb7d15583034c7faa&auto=format&fit=crop&w=500&q=60" alt="Interview Image" style="width:100%">
        </div>
    </div> 
    